version: '3'

services:
  php:
    build:
      context: .
      dockerfile: php-8.0.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
  php8.0:
    build:
      context: .
      dockerfile: php-8.0.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
