version: '3'

services:
  php:
    build:
      context: .
      dockerfile: php-7.3.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
  php7.4:
    build:
      context: .
      dockerfile: php-7.4.Dockerfile
    volumes:
      - .:/app
    working_dir: /app