name: Build

on:
  - push
  - workflow_dispatch

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }} (${{ matrix.composer-options }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        os:
          - ubuntu-latest
        composer-options:
          - ""
          - "--prefer-lowest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl
          coverage: xdebug
          ini-values: error_reporting=E_ALL

      - name: Install PHIVE
        uses: szepeviktor/phive@v1

      - name: Install dependencies
        run: composer update
          --prefer-dist
          --no-progress
          ${{ matrix.composer-options }}

      - name: Build application
        run: composer build

      - name: Run tests
        run: composer test

      - name: Run Infection
        run: composer infection
        env:
          INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}

      - name: Upload coverage to Codecov.io
        run: bash <(curl -s https://codecov.io/bash -s "build/logs")
        continue-on-error: true

      - name: Upload coverage to Scrutinizer
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: --format=php-clover build/logs/clover.xml
        continue-on-error: true
